export const PAYMENT_REQUIRED_HEADER = "PAYMENT-REQUIRED";
export const PAYMENT_SIGNATURE_HEADER = "PAYMENT-SIGNATURE";
export const PAYMENT_RESPONSE_HEADER = "PAYMENT-RESPONSE";
export const PAYMENT_IDENTIFIER_HEADER = "PAYMENT-IDENTIFIER";

export const LEGACY_PAYMENT_HEADER = "X-PAYMENT";
export const LEGACY_PAYMENT_RESPONSE_HEADER = "X-PAYMENT-RESPONSE";
export const LEGACY_PAYMENT_IDENTIFIER_HEADER = "X-PAYMENT-IDENTIFIER";

export const AUTH_CHALLENGE_TTL_MS = 5 * 60 * 1000;
export const AUTH_SESSION_TTL_MS = 15 * 60 * 1000;
export const DEFAULT_JOB_POLL_INTERVAL_MS = 5_000;

export const MARKETPLACE_NAME = "Fast Marketplace";
export const MARKETPLACE_VERSION = "0.1.0";
